Support Version 2.0.0 changes for approve-oam-request
openBackhaul/AdministratorAdministration pull request #146
Opened 2023-01-16 06:16 UTC by ManasaBM1

Fixes #133

2023-01-16 06:17 UTC, ManasaBM1 commented
Reviewer is @vanithavalluripalli9

2023-01-16 11:41 UTC, vanithavalluripalli9 requested changes

2023-01-16 11:41 UTC, vanithavalluripalli9 commented on server/service/AuthorizationApplication.js
> + * @file This module provides functionality to monitor the whether the registered application are approved within the required time.
please change the comment appropriately

2023-01-16 11:41 UTC, vanithavalluripalli9 commented on server/service/AuthorizationApplication.js
> +
Please add short comments for all the methods to understand about the method . Kindly change the file to path ../individualService folder

2023-01-16 12:58 UTC, vanithavalluripalli9 requested changes

2023-01-16 12:58 UTC, vanithavalluripalli9 commented on server/service/individualServices/AuthorizationApplication.js
> + * @file This module provides functionality to monitor the whether the registered application are approved within the required time.
Kindly , add the correct use of the module

2023-01-16 12:58 UTC, vanithavalluripalli9 commented on server/service/individualServices/AuthorizationApplication.js
> +     * @returns {promise} string {approvalStatus}
kindly , add param related information

2023-01-16 12:58 UTC, vanithavalluripalli9 commented on server/service/individualServices/AuthorizationApplication.js
> +**/
same as above

2023-01-17 16:45 UTC, vanithavalluripalli9 approved these changes
Changes looks good . Approved.

2023-01-17 16:45 UTC, merged