Implement OAM Services for version 2.0.0
openBackhaul/AdministratorAdministration pull request #150
Opened 2023-01-23 06:57 UTC by ManasaBM1

Fixes #141

2023-01-23 06:58 UTC, ManasaBM1 commented
Reviewer is @vanithavalluripalli9

2023-01-31 16:36 UTC, vanithavalluripalli9 requested changes
Please change the

2023-01-31 16:36 UTC, vanithavalluripalli9 commented on server/service/GenericResponseProfileService.js
> +    var examples = {};
Please change the name examples to response everywhere used , it would be more appropriate naming convention to be used

2023-02-02 17:43 UTC, vanithavalluripalli9 requested changes

2023-02-02 17:43 UTC, vanithavalluripalli9 commented on server/service/OperationClientService.js
> +      /****************************************************************************************
forwarding is not rquired for detailedLoggingIsOn attribute

2023-02-06 08:34 UTC, vanithavalluripalli9 approved these changes
Approved.

2023-02-06 08:35 UTC, merged