Reslove Update the approveOamRequest Service for the file does not exit and ALL method
openBackhaul/AdministratorAdministration pull request #174
Opened 2023-03-08 08:42 UTC by ManasaBM1

Fixes #173

2023-03-08 08:43 UTC, ManasaBM1 commented
Reviewer is @vanithavalluripalli9

2023-03-10 08:11 UTC, vanithavalluripalli9 requested changes

2023-03-10 08:11 UTC, vanithavalluripalli9 commented on server/service/IndividualServicesService.js
> +          let newReleaseTcpClientUuid = newReleaseTcpClientUuidList[0];
According to the issue , these changes are not required . Please remove the unwanted changes

2023-03-16 09:05 UTC, vanithavalluripalli9 requested changes

2023-03-21 06:20 UTC, vanithavalluripalli9 approved these changes

2023-03-21 06:20 UTC, merged