resolve update the bequeathYourDataAndDie method  and sotwareupgrade method
openBackhaul/AdministratorAdministration pull request #197
Opened 2023-04-10 12:58 UTC by ManasaBM1

Fixes #196

2023-04-10 12:59 UTC, ManasaBM1 commented
Reviewer is @vanithavalluripalli9

2023-04-18 13:48 UTC, vanithavalluripalli9 requested changes

2023-04-18 13:48 UTC, vanithavalluripalli9 commented on server/service/IndividualServicesService.js
>          let serverAddress = await tcpServerInterface.getLocalAddressOfTheProtocol(applicationProtocol);
We can remove the codeblock from line 194 to 199 as this will violate the idempotence concept

2023-05-10 12:49 UTC, PrathibaJee approved these changes
Requested changes are included. Thanks.

2023-05-10 12:56 UTC, vanithavalluripalli9 approved these changes

2023-05-10 12:56 UTC, merged