adding2.1.1version
openBackhaul/AdministratorAdministration pull request #311
Opened 2024-02-21 04:25 UTC by ManasaBM1

2024-02-21 04:26 UTC, ManasaBM1 commented
Reviewers is @PrathibaJee

2024-02-21 20:00 UTC, PrathibaJee requested changes

2024-02-21 20:00 UTC, PrathibaJee commented on server/index.js
Modify the server port to 3028.  Also update the same in the docker file.

2024-02-26 06:37 UTC, PrathibaJee approved these changes

2024-02-26 06:37 UTC, merged