newchange
openBackhaul/AdministratorAdministration pull request #386
Opened 2024-09-05 04:47 UTC by ManasaBM1

2024-09-05 05:08 UTC, ManasaBM1 commented
Reviewers is @PrathibaJee

2024-09-08 11:17 UTC, PrathibaJee approved these changes
Please resolve the review comments. Thanks.

2024-09-08 11:17 UTC, PrathibaJee commented on server/service/IndividualServicesService.js
> +      let stringProfileList = await stringProfile.getStringProfile('aa-2-1-2-string-p-001')
here you are getting a string profile , so attribute name shall be stringProfile instead of stringProfileList.

2024-09-08 11:17 UTC, PrathibaJee commented on server/service/IndividualServicesService.js
> +      let stringProfileList = await stringProfile.getStringProfile('aa-2-1-2-string-p-001')
Instead of retrieving the string profile by using the uuid , please using the string-name NameOfOperationForInquiringApprovals

2024-09-08 11:17 UTC, PrathibaJee commented on server/service/individualServices/AuthorizationApplication.js
> +exports.IsApplicationExists = async function (applicationaName, releaseNumber,authorization) {
change method name to isApplicationExists. change the typo in the argument "applicationaName" to "applicationName"

2024-09-08 11:17 UTC, PrathibaJee commented on server/service/individualServices/AuthorizationApplication.js
> +            const IsApplicationExistsIntheConfigFile= await getApplicationandReleaseNumberAtConfigFile(applicationaName,releaseNumber)
maintain lowerCamelCase in the variable declaration. change IsApplicationExistsIntheConfigFile to isApplicationExistsInTheConfigFile

2024-09-08 11:17 UTC, PrathibaJee commented on server/service/individualServices/AuthorizationApplication.js
> +    let isApplicationNameExit = false
typo in the variable declaration shall be corrected from isApplicationNameExit to isApplicationNameExist. Modify it in all the used references.

2024-09-08 11:17 UTC, PrathibaJee commented on server/service/individualServices/AuthorizationApplication.js
> +    let isReleaseNumberExit = false
typo in the variable declaration shall be corrected from isReleaseNumberExit to isReleaseNumberExist. Modify it in all the used references.

2024-09-08 11:17 UTC, PrathibaJee commented on server/service/individualServices/AuthorizationApplication.js
>      let isApplicationNameExit = {};
Correct the typo in the variable name from isApplicationNameExit to isApplicationNameExist. Modify it in all the used references.

2024-09-08 11:17 UTC, PrathibaJee commented on server/service/individualServices/AuthorizationApplication.js
>                      let allowAcees = registeredApplication[allowedSccess]
Correct the typo in the variable declaration from allowAcess to allowAccess. Also modify it in the used references.

2024-09-08 11:17 UTC, PrathibaJee commented on server/service/individualServices/AuthorizationApplication.js
> +async function ApplicationandReleaseNumber(applicationaName, authorization) {
Modify the function name as per the purpose of the functionality. From the underlying logic , "ApplicationandReleaseNumber" should not be the method name.

2024-09-08 11:17 UTC, PrathibaJee commented on server/service/individualServices/regardapplicationcallback.js
> +            let stringProfileList = await stringProfile.getStringProfile('aa-2-1-2-string-p-001')
Modify the variable name from stringProfileList to stringProfile as it will not hold a list.

2024-09-08 11:17 UTC, PrathibaJee commented on server/service/individualServices/regardapplicationcallback.js
> +            let stringProfileList = await stringProfile.getStringProfile('aa-2-1-2-string-p-001')
Instead of getting the string profile from the uuid , get it from the string-name NameOfOperationForInquiringApprovals

2024-09-08 11:18 UTC, PrathibaJee requested changes
Please resolve the review comments.

2024-09-10 07:59 UTC, PrathibaJee requested changes
Kindly please resolve the review comments. Thanks.

2024-09-10 07:59 UTC, PrathibaJee commented on server/service/StringProfileService.js
> +      let stringProfileList = await stringProfile.getStringValueAndPattern('NameOfOperationForInquiringApprovals')
For the putStringProfileStringValue , would'nt the uuid will be there as a part parameter ? Please get the uuid from the path parameter.

2024-09-10 07:59 UTC, PrathibaJee commented on server/service/individualServices/RegardApplication.js
> +    let StringValue ;
variable declaration shall be in lowerCamelCase.

2024-09-10 07:59 UTC, PrathibaJee commented on server/service/individualServices/RegardApplication.js
> +    let StringProfilePattern;
variable declaration shall be in lowerCamelCase.

2024-09-10 07:59 UTC, PrathibaJee commented on server/service/individualServices/regardapplicationcallback.js
>              let InquiringOamRequestCreateLinkForwardingName = "RegardApplicationCausesSequenceForInquiringBasicAuthRequestApprovals.CreateLinkForInquiringBasicAuthApprovals";
variable declaration shall be in lowerCamelCase.

2024-09-10 07:59 UTC, PrathibaJee commented on server/service/individualServices/regardapplicationcallback.js
>              let InquiringOamRequestCreateLinkRequestBody = {};
variable declaration shall be in lowerCamelCase.

2024-09-15 09:20 UTC, ManasaBM1 commented on server/service/IndividualServicesService.js
> +      let stringProfileList = await stringProfile.getStringProfile('aa-2-1-2-string-p-001')
resolved

2024-09-15 09:20 UTC, ManasaBM1 commented on server/service/IndividualServicesService.js
> +      let stringProfileList = await stringProfile.getStringProfile('aa-2-1-2-string-p-001')
resolved

2024-09-17 03:57 UTC, ManasaBM1 commented
Reviewers is @PrathibaJee

2024-09-18 04:39 UTC, PrathibaJee approved these changes
Thanks for resolving the review comments.

2024-09-18 04:39 UTC, merged