adding the response code changes
openBackhaul/AdministratorAdministration pull request #391
Opened 2024-09-20 10:34 UTC by ManasaBM1

2024-09-20 10:34 UTC, ManasaBM1 commented
Reviewers @PrathibaJee

2024-09-25 06:29 UTC, PrathibaJee requested changes

2024-09-25 06:29 UTC, PrathibaJee commented on server/service/IndividualServicesService.js
> +      if (Result.successConnected) {
SuccessConnected shall be successfullyConnected. Please change this occurrence in all the places.

2024-09-30 10:54 UTC, PrathibaJee approved these changes

2024-09-30 10:54 UTC, merged